[package]
name = "cosmic-clash"
version = "0.1.0"
edition = "2024"
license = "AGPL3.0"
description = "GUI of clash-rs"
repository = "https://github.com/pop-os/cosmic-app-template"


[features]
default = ["cosmic"]

# See https://github.com/pop-os/libcosmic/blob/master/Cargo.toml for available features.
cosmic = [
    "libcosmic/a11y", 
    "libcosmic/about", 
    "libcosmic/dbus-config", 
    "libcosmic/multi-window", 
    "libcosmic/single-instance", 
    "libcosmic/tokio", 
    "libcosmic/winit",
    "libcosmic/wgpu"
]

[dependencies]
futures-util = "0.3.31"
i18n-embed = { version = "0.16", features = [
    "fluent-system",
    "desktop-requester",
] }
i18n-embed-fl = "0.10"
open = "5.3.2"
rust-embed = "8.8.0"
tokio = { version = "1.48.0", features = ["full"] }

[target.'cfg(target_os = "linux")'.dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
features = ["wayland"]

[target.'cfg(not(target_os = "linux"))'.dependencies.libcosmic]
git = "https://github.com/pop-os/libcosmic.git"
features = []

# Uncomment to test a locally-cloned libcosmic
# [patch.'https://github.com/pop-os/libcosmic']
# libcosmic = { path = "../libcosmic" }
# cosmic-config = { path = "../libcosmic/cosmic-config" }
# cosmic-theme = { path = "../libcosmic/cosmic-theme" }
